### PR TITLE
Updated version / Support as of stable 1.0.1 / Updated Homey Zwave Dr…

### PR DESCRIPTION
**Pull request by mruiter**
…iver

Just the basic update to bring it back in to compliance of the first
stable release

### CODE REVIEW

**Comment by Thorarin** [comment]
Changes look fine, but I'm not able to actually test it right at this moment. I'll try to do the merge on Friday at the latest.

**Comment by Thorarin** [comment]
I'm personally still getting invalid_driver after these changes. Still investigating...

**Comment by mruiter** [comment]
I will also try to do some more testing this weekend. I could join again after zwave driver update. Maybee it was temporary

**Comment by Thorarin** [comment]
Looks like the main issue will be fixed on the Homey firmware side (https://github.com/athombv/homey/issues/1117), so I won't be merging this change to master.

For now, you can use your own fork or the driver-rename branch (they use different driver IDs), but you will have to redo the configuration if you switch back to the store app eventually.

**Pull request closed without merging**
